// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdJN1Q87qCPzcYBEHMhFGp1C64BQfKV9Q',
    appId: '1:35347068856:web:e8c8c502c31f3b404c014d',
    messagingSenderId: '35347068856',
    projectId: 'sliit-quick-book',
    authDomain: 'sliit-quick-book.firebaseapp.com',
    storageBucket: 'sliit-quick-book.firebasestorage.app',
    measurementId: 'G-MJNY9FZMFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6e8kelPjpGUZSSCJABO8wSifqux8ru7Y',
    appId: '1:35347068856:android:525fac062c0466aa4c014d',
    messagingSenderId: '35347068856',
    projectId: 'sliit-quick-book',
    storageBucket: 'sliit-quick-book.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNNsZkHR9tBOjFnMAmPgAB_jKvo8tpaiA',
    appId: '1:35347068856:ios:0d2159cbda719a0d4c014d',
    messagingSenderId: '35347068856',
    projectId: 'sliit-quick-book',
    storageBucket: 'sliit-quick-book.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNNsZkHR9tBOjFnMAmPgAB_jKvo8tpaiA',
    appId: '1:35347068856:ios:0d2159cbda719a0d4c014d',
    messagingSenderId: '35347068856',
    projectId: 'sliit-quick-book',
    storageBucket: 'sliit-quick-book.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdJN1Q87qCPzcYBEHMhFGp1C64BQfKV9Q',
    appId: '1:35347068856:web:d1ca08bf7920e9f54c014d',
    messagingSenderId: '35347068856',
    projectId: 'sliit-quick-book',
    authDomain: 'sliit-quick-book.firebaseapp.com',
    storageBucket: 'sliit-quick-book.firebasestorage.app',
    measurementId: 'G-7CB84S4CHG',
  );
}
