import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';

/// Material Design 3 design system.
///
/// The `ColorScheme`s below are hand-tuned rather than generated by
/// `ColorScheme.fromSeed`, whose tonal blending washes a brand colour
/// out into muted lavender surfaces. Primary is a crisp Material blue
/// (#0B57D0, light blue in dark), surfaces are clean cool whites over a
/// whisper-blue canvas, and tertiary is a warm terracotta counterpoint.
/// Every legacy token — `AppColors`, `AppText`, `AppShadows`,
/// `AppGradients` — resolves onto the scheme so all thirty screens
/// restyle together.
///
/// Colours resolve through getters so the app can flip to the dark
/// scheme at runtime; call sites keep the same `AppColors.x` syntax —
/// the trade-off is that colours can't appear inside `const`
/// expressions.
class AppColors {
  AppColors._();

  /// Hand-tuned light scheme: crisp blue, clean whites, warm tertiary.
  static const ColorScheme _lightScheme = ColorScheme.light(
    primary: Color(0xFF0B57D0),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD3E3FD),
    onPrimaryContainer: Color(0xFF041E49),
    secondary: Color(0xFF575E71),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFDBE2F9),
    onSecondaryContainer: Color(0xFF141B2C),
    tertiary: Color(0xFF9A4A26),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFDBCF),
    onTertiaryContainer: Color(0xFF351005),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFF4F6FB),
    onSurface: Color(0xFF191C20),
    onSurfaceVariant: Color(0xFF42474E),
    outline: Color(0xFF72777F),
    outlineVariant: Color(0xFFDEE2EA),
    inverseSurface: Color(0xFF2E3135),
    onInverseSurface: Color(0xFFEFF1F4),
    inversePrimary: Color(0xFFA8C7FA),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFFFFFFF),
    surfaceContainer: Color(0xFFEDF0F6),
    surfaceContainerHigh: Color(0xFFE6EAF1),
    surfaceContainerHighest: Color(0xFFE0E4EC),
    surfaceDim: Color(0xFFD4D9E2),
    surfaceBright: Color(0xFFF4F6FB),
  );

  /// Hand-tuned dark scheme: light primary, deep cool neutrals.
  static const ColorScheme _darkScheme = ColorScheme.dark(
    primary: Color(0xFFA8C7FA),
    onPrimary: Color(0xFF062E6F),
    primaryContainer: Color(0xFF0842A0),
    onPrimaryContainer: Color(0xFFD3E3FD),
    secondary: Color(0xFFBFC6DC),
    onSecondary: Color(0xFF293142),
    secondaryContainer: Color(0xFF3F4759),
    onSecondaryContainer: Color(0xFFDBE2F9),
    tertiary: Color(0xFFFFB69E),
    onTertiary: Color(0xFF551F0A),
    tertiaryContainer: Color(0xFF783115),
    onTertiaryContainer: Color(0xFFFFDBCF),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF101418),
    onSurface: Color(0xFFE1E2E8),
    onSurfaceVariant: Color(0xFFC2C7CF),
    outline: Color(0xFF8C9199),
    outlineVariant: Color(0xFF42474E),
    inverseSurface: Color(0xFFE1E2E8),
    onInverseSurface: Color(0xFF2E3135),
    inversePrimary: Color(0xFF0B57D0),
    surfaceContainerLowest: Color(0xFF0A0E12),
    surfaceContainerLow: Color(0xFF181C22),
    surfaceContainer: Color(0xFF1C2026),
    surfaceContainerHigh: Color(0xFF262A31),
    surfaceContainerHighest: Color(0xFF31353D),
    surfaceDim: Color(0xFF101418),
    surfaceBright: Color(0xFF363A41),
  );

  /// The scheme matching the active brightness. Kept in sync by the app
  /// root through [isDark] before the frame is built.
  static ColorScheme get scheme =>
      isDark ? _darkScheme : _lightScheme;

  /// Whether the dark palette is active. Synced by the app root from
  /// [AppState.themeMode] before the frame is built.
  static bool isDark = false;

  // Surfaces — M3 tonal tiers instead of white cards on an off-white page.
  static Color get background => scheme.surface;
  static Color get surface => scheme.surfaceContainerLow;
  static Color get surfaceMuted => scheme.surfaceContainer;
  static Color get surfaceSunken => scheme.surfaceContainerHighest;

  // Brand — the primary roles. Lift is a brighter vivid blue (light mode)
  // or a deeper one (dark), never a grey blend.
  static Color get primary => scheme.primary;
  static Color get primaryDark => scheme.onPrimaryContainer;
  static Color get primarySoft => scheme.primaryContainer;
  static Color get primaryBright => scheme.primary;
  static Color get primaryLift => isDark
      ? Color.lerp(scheme.primary, Colors.black, 0.25)!
      : Color.lerp(scheme.primary, Colors.white, 0.22)!;

  // Accents — tertiary is the seeded warm complement, secondary the
  // quiet counterpart.
  static Color get accent => scheme.tertiary;
  static Color get accentSoft => scheme.tertiaryContainer;
  static Color get cyan => scheme.secondary;
  static Color get cyanSoft => scheme.secondaryContainer;
  static Color get gold =>
      isDark ? const Color(0xFFF2BC4C) : const Color(0xFF8A5A00);
  static Color get goldSoft =>
      Color.alphaBlend(gold.withValues(alpha: 0.12), scheme.surface);

  // Text — M3 foreground roles.
  static Color get textPrimary => scheme.onSurface;
  static Color get textSecondary => scheme.onSurfaceVariant;
  static Color get textFaint => scheme.outline;
  static Color get textInverse => scheme.onPrimary;

  // Lines — M3 outline roles.
  static Color get border => scheme.outlineVariant;
  static Color get borderStrong => scheme.outline;

  // Status — semantic tonal pairs blended over the surface so they sit
  // harmonically inside the scheme in both brightnesses.
  static Color get success =>
      isDark ? const Color(0xFF7ED99C) : const Color(0xFF17724A);
  static Color get successSoft =>
      Color.alphaBlend(success.withValues(alpha: 0.12), scheme.surface);
  static Color get warning =>
      isDark ? const Color(0xFFFFB95C) : const Color(0xFF9A6300);
  static Color get warningSoft =>
      Color.alphaBlend(warning.withValues(alpha: 0.12), scheme.surface);
  static Color get error => scheme.error;
  static Color get errorSoft =>
      Color.alphaBlend(error.withValues(alpha: 0.10), scheme.surface);
  static Color get info => primary;
  static Color get infoSoft =>
      Color.alphaBlend(primary.withValues(alpha: 0.10), scheme.surface);
  static Color get neutral => scheme.onSurfaceVariant;
  static Color get neutralSoft => scheme.surfaceContainerHigh;

  // Seat map
  static Color get seatAvailable => success;
  static Color get seatLimited => warning;
  static Color get seatOccupied => error;
  static Color get seatSelected => accent;

  /// ARGB values, so they line up with `Book.coverColor`.
  static const List<int> coverPalette = [
    0xFF0B57D0,
    0xFF2A5B5B,
    0xFF8D3B2A,
    0xFFB06F17,
    0xFF4A3E72,
    0xFF1F4E5B,
    0xFF7C3626,
    0xFF3B5E34,
  ];
}

/// The M3 corner scale: extra-small 8, small 12, medium 16, large 20,
/// extra-large 28, full (stadium).
class AppRadii {
  AppRadii._();

  static const xs = 8.0;
  static const sm = 12.0;
  static const md = 16.0;
  static const lg = 20.0;
  static const xl = 28.0;
  static const full = 999.0;
}

/// Elevation shadows tuned to the M3 key-light model: a tight key shadow
/// plus a wide ambient one. Tinted variants keep the option of a coloured
/// bloom for featured surfaces.
class AppShadows {
  AppShadows._();

  static List<BoxShadow> get card => [
        BoxShadow(
          color: Colors.black.withValues(alpha: 0.06),
          blurRadius: 10,
          offset: const Offset(0, 3),
        ),
      ];

  static List<BoxShadow> get raised => [
        BoxShadow(
          color: Colors.black.withValues(alpha: 0.08),
          blurRadius: 16,
          offset: const Offset(0, 5),
        ),
        BoxShadow(
          color: Colors.black.withValues(alpha: 0.05),
          blurRadius: 32,
          offset: const Offset(0, 12),
        ),
      ];

  /// Two-part coloured shadow: a soft neutral drop plus a tinted bloom in
  /// the card's own hue. This is what makes surfaces read as layered.
  static List<BoxShadow> layered(Color tint) => [
        BoxShadow(
          color: tint.withValues(alpha: 0.14),
          blurRadius: 20,
          offset: const Offset(0, 8),
        ),
        BoxShadow(
          color: Colors.black.withValues(alpha: 0.05),
          blurRadius: 36,
          offset: const Offset(0, 16),
        ),
      ];

  /// Soft ambient bloom, for primary actions and selected states.
  static List<BoxShadow> glow(Color tint) => [
        BoxShadow(
          color: tint.withValues(alpha: 0.25),
          blurRadius: 18,
          offset: const Offset(0, 6),
        ),
        BoxShadow(
          color: tint.withValues(alpha: 0.15),
          blurRadius: 32,
          offset: const Offset(0, 12),
        ),
      ];

  static List<BoxShadow> get primary =>
      glow(AppColors.primary.withValues(alpha: 0.85));
}

/// Brand gradients resolved from the seeded scheme, so they re-hue with
/// light/dark mode instead of being fixed navy. (These were `const`
/// before the M3 pass; they can no longer be.)
class AppGradients {
  AppGradients._();

  /// Primary → deep primary. The logo mark and small brand blocks.
  static Gradient get brand => LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [
          AppColors.primary,
          Color.lerp(AppColors.primary, Colors.black, 0.30)!,
        ],
      );

  /// Vertical primary ramp behind hero panels.
  static Gradient get hero => LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: [
          AppColors.primary,
          Color.lerp(AppColors.primary, Colors.black, 0.25)!,
        ],
      );

  /// The signature sweep: vivid primary through its lift into the warm
  /// terracotta, hand-picked so the blue-to-warm jump doesn't muddy into
  /// purple the way a plain RGB blend would.
  static Gradient get aurora {
    if (AppColors.isDark) {
      return const LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [Color(0xFF0B3A8F), Color(0xFF1254C4), Color(0xFF7A3517)],
      );
    }
    return const LinearGradient(
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
      colors: [Color(0xFF0B57D0), Color(0xFF3E6FD8), Color(0xFFC85A32)],
    );
  }

  static Gradient get auroraSoft => LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [
          Color.alphaBlend(
              AppColors.primary.withValues(alpha: 0.10), AppColors.background),
          Color.alphaBlend(
              AppColors.accent.withValues(alpha: 0.08), AppColors.background),
        ],
      );

  static Gradient get mint => LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [
          AppColors.success,
          Color.lerp(AppColors.success, Colors.black, 0.25)!,
        ],
      );

  /// Deep panel used behind stats and staff surfaces — deliberately a
  /// fixed dark slate in both brightnesses, since its content is always
  /// light-on-dark.
  static const Gradient panel = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFF232E3D), Color(0xFF121826)],
  );

  static Gradient tint(Color color) => LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [color.withValues(alpha: 0.12), color.withValues(alpha: 0.04)],
      );

  static LinearGradient cover(int baseColor) {
    final base = Color(baseColor);
    return LinearGradient(
      begin: Alignment.topCenter,
      end: Alignment.bottomCenter,
      colors: [
        Color.alphaBlend(const Color(0x2EFFFFFF), base),
        base,
        Color.alphaBlend(const Color(0x26000000), base),
      ],
    );
  }
}

/// Material 3 type ramp on Inter font.
/// Display/title roles use tight negative tracking, body and label sit
/// neutral, per modern iOS/Android best practices.
class AppText {
  AppText._();

  static TextStyle display(
    double size, {
    FontWeight w = FontWeight.w700,
    double ls = -0.5,
    Color? color,
    double? height,
  }) =>
      GoogleFonts.inter(
        fontSize: size,
        fontWeight: w,
        letterSpacing: ls,
        color: color ?? AppColors.textPrimary,
        height: height ?? 1.15,
      );

  static TextStyle title(
    double size, {
    FontWeight w = FontWeight.w600,
    double ls = -0.15,
    Color? color,
    double? height,
  }) =>
      GoogleFonts.inter(
        fontSize: size,
        fontWeight: w,
        letterSpacing: ls,
        color: color ?? AppColors.textPrimary,
        height: height ?? 1.25,
      );

  static TextStyle body(
    double size, {
    FontWeight w = FontWeight.w400,
    double ls = 0,
    Color? color,
    double? height,
  }) =>
      GoogleFonts.inter(
        fontSize: size,
        fontWeight: w,
        letterSpacing: ls,
        color: color ?? AppColors.textPrimary,
        height: height,
      );

  static TextStyle label(
    double size, {
    FontWeight w = FontWeight.w600,
    double ls = 0.1,
    Color? color,
  }) =>
      GoogleFonts.inter(
        fontSize: size,
        fontWeight: w,
        letterSpacing: ls,
        color: color ?? AppColors.textSecondary,
      );

  /// The small uppercase section headers used above lists.
  static TextStyle overline(
    double size, {
    FontWeight w = FontWeight.w700,
    double ls = 1.2,
    Color? color,
  }) =>
      GoogleFonts.inter(
        fontSize: size,
        fontWeight: w,
        letterSpacing: ls,
        color: color ?? AppColors.textFaint,
      );
}

class AppTheme {
  AppTheme._();

  static ThemeData light() => _build(Brightness.light);

  static ThemeData dark() => _build(Brightness.dark);

  static ThemeData _build(Brightness brightness) {
    final dark = brightness == Brightness.dark;
    final scheme = dark
        ? AppColors._darkScheme
        : AppColors._lightScheme;

    return ThemeData(
      useMaterial3: true,
      brightness: brightness,
      colorScheme: scheme,
      scaffoldBackgroundColor: scheme.surface,
      splashFactory: InkSparkle.splashFactory,
      appBarTheme: AppBarTheme(
        backgroundColor: scheme.surface,
        foregroundColor: scheme.onSurface,
        elevation: 0,
        scrolledUnderElevation: 2,
        centerTitle: true,
        titleTextStyle: AppText.title(17, w: FontWeight.w600),
        iconTheme: const IconThemeData(size: 22),
        systemOverlayStyle: dark
            ? SystemUiOverlayStyle.light
            : SystemUiOverlayStyle.dark,
      ),
      cardTheme: CardThemeData(
        color: scheme.surfaceContainerLow,
        elevation: 0,
        margin: EdgeInsets.zero,
        clipBehavior: Clip.antiAlias,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppRadii.md),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: scheme.surfaceContainerHigh,
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 15),
        hintStyle: AppText.body(14.5, color: scheme.onSurfaceVariant),
        labelStyle: AppText.body(13.5, color: scheme.onSurfaceVariant),
        floatingLabelStyle:
            AppText.body(13, w: FontWeight.w600, color: scheme.primary),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(AppRadii.sm),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(AppRadii.sm),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(AppRadii.sm),
          borderSide: BorderSide(color: scheme.primary, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(AppRadii.sm),
          borderSide: BorderSide(color: scheme.error),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(AppRadii.sm),
          borderSide: BorderSide(color: scheme.error, width: 2),
        ),
        prefixIconColor: scheme.onSurfaceVariant,
        suffixIconColor: scheme.onSurfaceVariant,
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          backgroundColor: scheme.primary,
          foregroundColor: scheme.onPrimary,
          elevation: 0,
          minimumSize: const Size.fromHeight(52),
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 15),
          shape: const StadiumBorder(),
          textStyle: AppText.title(15, w: FontWeight.w600),
        ),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: scheme.primary,
          foregroundColor: scheme.onPrimary,
          elevation: 0,
          shadowColor: Colors.transparent,
          minimumSize: const Size.fromHeight(52),
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 15),
          shape: const StadiumBorder(),
          textStyle: AppText.title(15, w: FontWeight.w600),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: scheme.primary,
          minimumSize: const Size.fromHeight(52),
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 15),
          side: BorderSide(color: scheme.outline, width: 1.2),
          shape: const StadiumBorder(),
          textStyle: AppText.title(15, w: FontWeight.w600),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: scheme.primary,
          textStyle: AppText.title(14, w: FontWeight.w600),
        ),
      ),
      listTileTheme: ListTileThemeData(
        iconColor: scheme.onSurfaceVariant,
        titleTextStyle: AppText.title(15, w: FontWeight.w600),
        subtitleTextStyle: AppText.body(13, color: scheme.onSurfaceVariant),
      ),
      switchTheme: SwitchThemeData(
        thumbColor: WidgetStateProperty.resolveWith(
          (states) => states.contains(WidgetState.selected)
              ? scheme.onPrimary
              : scheme.outline,
        ),
        trackColor: WidgetStateProperty.resolveWith(
          (states) => states.contains(WidgetState.selected)
              ? scheme.primary
              : scheme.surfaceContainerHighest,
        ),
        trackOutlineColor: WidgetStateProperty.resolveWith(
          (states) => states.contains(WidgetState.selected)
              ? Colors.transparent
              : scheme.outlineVariant,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: WidgetStateProperty.resolveWith(
          (states) => states.contains(WidgetState.selected)
              ? scheme.primary
              : Colors.transparent,
        ),
        checkColor: WidgetStatePropertyAll(scheme.onPrimary),
        side: BorderSide(color: scheme.outline, width: 1.6),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(5),
        ),
      ),
      chipTheme: ChipThemeData(
        backgroundColor: scheme.surfaceContainerLow,
        selectedColor: scheme.secondaryContainer,
        labelStyle: AppText.label(13, color: scheme.onSurfaceVariant),
        secondaryLabelStyle:
            AppText.label(13, color: scheme.onSecondaryContainer),
        side: BorderSide(color: scheme.outlineVariant),
        shape: const StadiumBorder(),
      ),
      dividerTheme: DividerThemeData(
        color: scheme.outlineVariant,
        thickness: 1,
        space: 1,
      ),
      snackBarTheme: SnackBarThemeData(
        behavior: SnackBarBehavior.floating,
        backgroundColor: scheme.inverseSurface,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppRadii.sm),
        ),
        contentTextStyle:
            AppText.body(13.5, color: scheme.onInverseSurface),
      ),
      bottomSheetTheme: BottomSheetThemeData(
        backgroundColor: scheme.surfaceContainerLow,
        surfaceTintColor: Colors.transparent,
        showDragHandle: true,
        dragHandleColor: scheme.outlineVariant,
        shape: const RoundedRectangleBorder(
          borderRadius:
              BorderRadius.vertical(top: Radius.circular(AppRadii.xl)),
        ),
      ),
      dialogTheme: DialogThemeData(
        backgroundColor: scheme.surfaceContainerLow,
        surfaceTintColor: Colors.transparent,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppRadii.xl),
        ),
      ),
      progressIndicatorTheme:
          ProgressIndicatorThemeData(color: scheme.primary),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: scheme.primaryContainer,
        foregroundColor: scheme.onPrimaryContainer,
        elevation: 0,
        highlightElevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppRadii.lg),
        ),
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: scheme.surfaceContainer,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        height: 72,
        indicatorColor: scheme.primaryContainer,
        labelBehavior: NavigationDestinationLabelBehavior.alwaysShow,
        iconTheme: WidgetStateProperty.resolveWith(
          (states) => IconThemeData(
            size: 23,
            color: states.contains(WidgetState.selected)
                ? scheme.onPrimaryContainer
                : scheme.onSurfaceVariant,
          ),
        ),
        labelTextStyle: WidgetStateProperty.resolveWith(
          (states) => AppText.label(
            11.5,
            w: states.contains(WidgetState.selected)
                ? FontWeight.w700
                : FontWeight.w500,
            color: states.contains(WidgetState.selected)
                ? scheme.onSurface
                : scheme.onSurfaceVariant,
          ),
        ),
      ),
      tabBarTheme: TabBarThemeData(
        labelColor: scheme.primary,
        unselectedLabelColor: scheme.onSurfaceVariant,
        indicatorColor: scheme.primary,
        dividerColor: scheme.outlineVariant,
      ),
      pageTransitionsTheme: const PageTransitionsTheme(
        builders: {
          TargetPlatform.android: _SoftPageTransitionsBuilder(),
          TargetPlatform.iOS: _SoftPageTransitionsBuilder(),
          TargetPlatform.windows: _SoftPageTransitionsBuilder(),
          TargetPlatform.macOS: _SoftPageTransitionsBuilder(),
          TargetPlatform.linux: _SoftPageTransitionsBuilder(),
        },
      ),
    );
  }
}

class _SoftPageTransitionsBuilder extends PageTransitionsBuilder {
  const _SoftPageTransitionsBuilder();

  @override
  Widget buildTransitions<T>(
    PageRoute<T> route,
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    final curved = CurvedAnimation(
      parent: animation,
      curve: Curves.easeOutCubic,
      reverseCurve: Curves.easeInCubic,
    );
    return FadeTransition(
      opacity: curved,
      child: SlideTransition(
        position: Tween<Offset>(
          begin: const Offset(0, 0.03),
          end: Offset.zero,
        ).animate(curved),
        child: child,
      ),
    );
  }
}
